CREATE TABLE stg_beneficiary (
    BeneID VARCHAR(20),
    DOB VARCHAR(20),
    DOD VARCHAR(20),
    Gender VARCHAR(5),
    Race VARCHAR(5),
    RenalDiseaseIndicator VARCHAR(5),
    State VARCHAR(10),
    County VARCHAR(10),
    NoOfMonths_PartACov VARCHAR(5),
    NoOfMonths_PartBCov VARCHAR(5),

    ChronicCond_Alzheimer VARCHAR(5),
    ChronicCond_Heartfailure VARCHAR(5),
    ChronicCond_KidneyDisease VARCHAR(5),
    ChronicCond_Cancer VARCHAR(5),
    ChronicCond_ObstrPulmonary VARCHAR(5),
    ChronicCond_Depression VARCHAR(5),
    ChronicCond_Diabetes VARCHAR(5),
    ChronicCond_IschemicHeart VARCHAR(5),
    ChronicCond_Osteoporasis VARCHAR(5),
    ChronicCond_rheumatoidarthritis VARCHAR(5),
    ChronicCond_stroke VARCHAR(5),

    IPAnnualReimbursementAmt VARCHAR(20),
    IPAnnualDeductibleAmt VARCHAR(20),
    OPAnnualReimbursementAmt VARCHAR(20),
    OPAnnualDeductibleAmt VARCHAR(20)
);

CREATE TABLE stg_ip (BeneID varchar(15),
ClaimID varchar(15),
ClaimStartDt varchar(15),
ClaimEndDt varchar(15),
Provider varchar(15),
InscClaimAmtReimbursed varchar(15),
AttendingPhysician varchar(15),
OperatingPhysician varchar(15),
OtherPhysician varchar(15),
AdmissionDt varchar(15),
ClmAdmitDiagnosisCode varchar(15),
DeductibleAmtPaid varchar(15),
DischargeDt varchar(15),
DiagnosisGroupCode varchar(5),
ClmDiagnosisCode_1 varchar(5),
ClmDiagnosisCode_2 varchar(5),
ClmDiagnosisCode_3 varchar(5),
ClmDiagnosisCode_4 varchar(5),
ClmDiagnosisCode_5 varchar(5),
ClmDiagnosisCode_6 varchar(5),
ClmDiagnosisCode_7 varchar(5),
ClmDiagnosisCode_8 varchar(5),
ClmDiagnosisCode_9 varchar(5),
ClmDiagnosisCode_10 varchar(5),
ClmProcedureCode_1 varchar(5),
ClmProcedureCode_2 varchar(5),
ClmProcedureCode_3 varchar(5),
ClmProcedureCode_4 varchar(5),
ClmProcedureCode_5 varchar(5),
ClmProcedureCode_6 varchar(5));

CREATE TABLE stg_op (BeneID varchar(15),
ClaimID varchar(15),
ClaimStartDt varchar(15),
ClaimEndDt varchar(15),
Provider varchar(15),
InscClaimAmtReimbursed varchar(15),
AttendingPhysician varchar(15),
OperatingPhysician varchar(15),
OtherPhysician varchar(15),
ClmDiagnosisCode_1 varchar(5),
ClmDiagnosisCode_2 varchar(5),
ClmDiagnosisCode_3 varchar(5),
ClmDiagnosisCode_4 varchar(5),
ClmDiagnosisCode_5 varchar(5),
ClmDiagnosisCode_6 varchar(5),
ClmDiagnosisCode_7 varchar(5),
ClmDiagnosisCode_8 varchar(5),
ClmDiagnosisCode_9 varchar(5),
ClmDiagnosisCode_10 varchar(5),
ClmProcedureCode_1 varchar(5),
ClmProcedureCode_2 varchar(5),
ClmProcedureCode_3 varchar(5),
ClmProcedureCode_4 varchar(5),
ClmProcedureCode_5 varchar(5),
ClmProcedureCode_6 varchar(5),
DeductibleAmtPaid varchar(15),
ClmAdmitDiagnosisCode varchar(5));


create table stg_provider( Provider varchar(15),
PotentialFraud varchar(5));

